# Generated by Django 3.1.4 on 2020-12-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password1',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='password2',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
