# Generated by Django 3.1.4 on 2021-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
