# Generated by Django 3.1.4 on 2021-01-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210109_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanteenEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(default='DEFAULT VALUE', max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('loginId', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
