# Generated by Django 3.1.4 on 2021-01-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20210110_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canteenemployee',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Enter email', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
