# Generated by Django 3.1.4 on 2021-01-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
