# Generated by Django 3.1.4 on 2021-01-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20210111_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
