# Generated by Django 3.1.4 on 2021-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_remove_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
